### PR TITLE
New OpenTSDB module

### PR DESCRIPTION
**Pull request by kennethleider**
I started with your Influxdb module, and converted it to write to OpenTSDB.  So this should not be merged back into the kamon-influxdb.

I am probably not completely done with the code right now, but I wanted to see if you wanted it sooner rather than later.  So please let me know if you are interested.

### CODE REVIEW

**Comment by dpsoft** [comment]
hey @kennethleider I think is really interesting module for the Kamon ecosystem, maybe we can create a new repository  `kamon-opentsdb` and you can do a PR there. @ivantopo WDYT?

**Comment by kennethleider** [comment]
I think that sounds great.  Do you need me to add licensing information and
headers, or can you do that?

**Comment by dpsoft** [comment]
@kennethleider please make the PR here: https://github.com/kamon-io/kamon-opentsdb

**Comment by kennethleider** [comment]
I have a new sprint tomorrow, I am going to try to allocate some time to
writing more unit tests.  You can expect the PR on Thursday,

**Comment by dpsoft** [comment]
close in favor of https://github.com/kamon-io/kamon-opentsdb/pull/1

**Pull request closed without merging**
