### PR TITLE
Support for protocol=https

### PR DESCRIPTION
**Pull request by dsolonenko**

### CODE REVIEW

**Comment by anarwal27** [comment]
Great @dsolonenko, looking forward to see this merged in master.

**Comment by dpsoft** [comment]
@dsolonenko  thanks for proposing this PR, please sign our [CLA](https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform) and  we are good to go!

**Comment by dsolonenko** [comment]
@dpsoft done

**Comment by dpsoft** [comment]
@dsolonenko done!!

**Comment by dpsoft** [comment]
@dsolonenko @anarwal27 I just published the `0.6.9` version with this changes.

**Pull request merged**
