### PR TITLE
Allow https protocol

### PR DESCRIPTION
**Pull request by Qthunder**
Allow user to specific the protocol needed to connect to their remote influx instance. At the moment this is hard-coded as `http`.

### CODE REVIEW

**Comment by Qthunder** [comment]
The test edit is a bit clunky, welcome to suggestions.

**Comment by ivantopo** [comment]
Hey @Qthunder, this change looks good! There are some conflicts now, though, do you maybe have some time resolve them? I can resolve them and merge, but I will still ask you to please [electronically sign](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) the CLA before this can be merged. Thanks!

**Comment by Qthunder** [comment]
Hey! Thanks for taking a look. I'll try to get around to solving conflicts this week. If you get there before me, I signed the CLA :)

**Comment by Qthunder** [comment]
Conflicts resolved @ivantopo  :)

**Comment by martin-g** [comment]
@ivantopo Any ETA when this could be merged and released ?

**Comment by dpsoft** [comment]
@Qthunder thanks for proposing this PR!

**Comment by dpsoft** [comment]
@Qthunder @martin-g done! https://github.com/kamon-io/kamon-influxdb/releases/tag/v1.0.2

**Comment by martin-g** [comment]
@dpsoft Thank you, but it seems you didn't see my comment in the original issue. I was able to overcome the problem with the hardcoded protocol via Java Reflection and then I hit the next problem - the http call failed because it was not authenticated. So I had to use reflection to provide custom http client too.
I've just created https://github.com/kamon-io/kamon-influxdb/issues/28 for it.
I can keep using my hack until the next release because it is done once at the start of the application, but a new release would be very welcome too!

**Pull request merged**
