### PR TITLE
Implement basic-authentication for InfluxDB requests

### LINKED ISSUE #21: Authentication no-longer works
It seems that configuration like the following:

```
kamon {
  influxdb {

    authentication {
      user = "my-user",
      password = "my-password"
    }
  }
}
```

No longer works.
I guess there is missing configuration of Authenticator when building the client:
https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/scala/kamon/influxdb/InfluxDBReporter.scala#L136

### PR DESCRIPTION
**Pull request by bjgbeelen**
The Kamon-InfluxDB extension that worked with kamon 0.6.x allowed for specifying
username + password for InfluxDB. This functionality has been lost with the
current implementation. The previous implementation was insecure passing the
password as a query parameter in the URL. Using basic authentication, which
the OkHttpClient supports, we have a more secure way of passing this information.

This fixes #21 
This is a more secure solution than provided in #25

### CODE REVIEW

**Comment by Qthunder** [comment]
This is indeed better than my approach, which just looked for a quick & dirty solution. Bump 👍

**Comment by pawelgrzes** [comment]
👍

**Comment by ivantopo** [comment]
hey @bjgbeelen, this looks nice! Could you please [electronically sign](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) the CLA so that we can merge this?

**Comment by bjgbeelen** [comment]
@ivantopo done!

**Pull request merged**
